### PR TITLE
Add a post about deploying secure web apps on Carina

### PR DESCRIPTION
**Pull request by larsbutler**
... using SSL, Cloud Load Balancers, and Docker.

Moved from https://github.com/rackerlabs/docs-developer-blog/pull/139.

The images I've included are pretty raw and large. Please let me know if they should be resized or edited in any way.

### CODE REVIEW

**Comment by rgbkrk** [comment]
Cool!

**Comment by rgbkrk** [comment]
Want to update the dates on this?

**Comment by larsbutler** [comment]
@rgbkrk Which dates?

**Comment by rgbkrk** [comment]
For some reason I read it as a date in the past, I now see it's a date several weeks from now. We'll just want to update with the right date before we publish.

@kmsholcomb - care to review?

**Comment by kmsholcomb** [comment]
@rgbkrk. Yes. I will leave comments today.

**Comment by rgbkrk** [comment]
Thank you!

**Comment by kmsholcomb** [comment]
Wow, this is much longer than I anticipated! I'll leave my editorial comments either tonight or first thing in the morning. Sorry for the delay!

**Comment by rgbkrk** [comment]
It's ok, you've got time here.

**Comment by larsbutler** [comment]
> Wow, this is much longer than I anticipated! I'll leave my editorial comments either tonight or first thing in the morning. Sorry for the delay!

@kmsholcomb FWIW, this has already been through a round of review/comments, in case you want to look over those: https://github.com/rackerlabs/docs-developer-blog/pull/139. Any other feedback is welcome of course!

**Comment by kmsholcomb** [comment]
Hi @larsbutler. My comments are strictly editorial (I am the editor for the Carina team and the docs writers in DevEx), and they are probably more involved than you are used to seeing for blog posts simply because we want to have some consistency in the Carina content. Because the post is a long one and provides lots of detailed steps, I made suggestions for adding subheadings in some sections and also for using more step numbering. The subsections and especially the numbering will help users move through the post and keep their place. I also tried to standardize on using second person “you” throughout most of the steps, rather than alternating between “you” and “we” or “us.” I think that is clearer and keeps the focus on the user. Otherwise, most of my edits are around tightening up language here and there, and applying some of our formatting guidelines (for example, making UI field names bold rather than monospace, and using sentence-style capitalization for headings). 

Because of the structural nature of some of my edits, I am attaching a Word doc with markup rather than leaving comments directly in the file here on GitHub. (I always cringe when sending a Word doc to a developer, but it really is the best way to show markup!) The markup is pretty straightforward, I hope. Suggested additions and replacements to text appear inline in red, and deleted text appears in the sidebar (in Word, on the Review tab, be sure to select to show revisions in balloons). Comments and questions also appear in the sidebar.

Please let me know if you have any questions about any of my suggestions. Thanks! 

[Deploying secure web applications on the Rackspace Cloud with Carina and Docker_editsKH.docx](https://github.com/getcarina/getcarina.com/files/51075/Deploying.secure.web.applications.on.the.Rackspace.Cloud.with.Carina.and.Docker_editsKH.docx)

**Comment by larsbutler** [comment]
@kmsholcomb Thanks for the comments and editing! This is really helpful.

I've gotten through most of the edits, and now I'm tuning up the markdown (fixing ordered list formatting, bolding, etc.). I'll give you you a "thumbs up" when it's ready for another look.

**Comment by larsbutler** [comment]
@kmsholcomb @rgbkrk Okay, edits are done. I've amended the original commit (in order to not clutter the commit history). Let me know if you find any other issues!

**Comment by rgbkrk** [comment]
The only things I'd change now are the date of the post (in the front matter) as well as the filename to match today's date, and then we ship it.

**Comment by larsbutler** [comment]
@rgbkrk 

> The only things I'd change now are the date of the post (in the front matter) as well as the filename to match today's date, and then we ship it.

Okay, cool. What about the time, in the post header? Does that matter?

**Comment by rgbkrk** [comment]
> Okay, cool. What about the time, in the post header? Does that matter?

It affects the order in which any other posts from today would go up. That one is not a big deal.

**Comment by rgbkrk** [comment]
On a related note, we should be able to [help folks with letsencrypt](https://getcarina.com/blog/weekly-news-docker-sock-letsencrypt/) + LBs in a follow up post.

**Comment by larsbutler** [comment]
@rgbkrk 

> On a related note, we should be able to help folks with letsencrypt + LBs in a follow up post.

Oh cool! A couple of my teammates were trying to use Let's Encrypt the other day to automate some SSL stuff, and I think they'll find this useful.

**Comment by rgbkrk** [comment]
:shipit:

**Comment by rgbkrk** [comment]
Thanks again @larsbutler!

Looks like we've got some troubles on our presenters at the moment, your post won't be up for a little bit.

**Pull request merged**
