### PR TITLE
OAuth integration reference guide

### PR DESCRIPTION
**Pull request by carolynvs**

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-1bf3f245a0/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-89a95baa7f/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-83b5fae7ca/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-9b2478c5a6/). :bow:

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-85b6c1f5d0/)

**Comment by carolynvs** [comment]
Here is the preview page: https://staging.developer.rackspace.com/getcarina.com/build-85b6c1f5d0/docs/reference/oauth-integration/

**Comment by mdarby** [comment]
:+1:

**Comment by kmsholcomb** [comment]
Hi @carolynvs. My suggested edits and some comments and questions are in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[OAuth Integration_editsKH.pdf](https://github.com/getcarina/getcarina.com/files/208797/OAuth.Integration_editsKH.pdf)
[OAuth Integration_editsKH.docx](https://github.com/getcarina/getcarina.com/files/208798/OAuth.Integration_editsKH.docx)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-07b38ce3f7/). :bow:

**Pull request merged**
