### PR TITLE
Weekly news for 2016-04-08

### LINKED ISSUE #801: Weekly news blog post for 2016-04-08
- [x] Docker 1.10.3 and Docker Swarm 1.1.3
- [x] Carina OAuth
- [x] Upcoming reboot
- [x] [How do I even Swarm?](http://everett-toews.github.io/effective-docker-swarm/slides/#/welcome)

### PR DESCRIPTION
**Pull request by carolynvs**
Closes #801

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-c3ad2fefb1/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-c3ad2fefb1/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-aa0aac61b7/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-39bef80225/). :bow:

**Comment by kmsholcomb** [comment]
Hi @carolynvs: Just a few minor edits in the attached Word doc (and PDF copy of it). Please let me know if you have any questions. Thanks!

[Weekly news_4-8-2016.pdf](https://github.com/getcarina/getcarina.com/files/210728/Weekly.news_4-8-2016.pdf)
[Weekly news_4-8-2016.docx](https://github.com/getcarina/getcarina.com/files/210727/Weekly.news_4-8-2016.docx)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-5696fde745/).

**Pull request merged**
