### PR TITLE
New carina cli syntax

### PR DESCRIPTION
**Pull request by carolynvs**
Update examples with the new cli syntax and commands.

### CODE REVIEW

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-d87b906962/)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-07fafc1264/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-c1e81c3a36/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-ca14cf3fd2/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-fb271f8982/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-e7f820ccd7/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-604ee161e2/)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-2d1528b852/).

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-32a5c92980/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-2140ca0466/). :bow:

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-377577b6de/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-f13f0d5917/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-ca82dbdf55/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-ece4f71b84/)

**Comment by kmsholcomb** [comment]
Hi @carolynvs. My edits are in the attached Word docs (and PDF copies of them--sometimes the PDFs are easier to read!). Please let me know if you have any questions. Thanks!

[Carina CLI_editsKH.pdf](https://github.com/getcarina/getcarina.com/files/562783/Carina.CLI_editsKH.pdf)
[Carina CLI_editsKH.docx](https://github.com/getcarina/getcarina.com/files/562786/Carina.CLI_editsKH.docx)
[Getting started with the Carina CLI_update_editsKH.pdf](https://github.com/getcarina/getcarina.com/files/562785/Getting.started.with.the.Carina.CLI_update_editsKH.pdf)
[Getting started with the Carina CLI_update_editsKH.docx](https://github.com/getcarina/getcarina.com/files/562784/Getting.started.with.the.Carina.CLI_update_editsKH.docx)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-139d3666f2/)

**Pull request merged**
