### PR TITLE
Make k8's zero to hero tutorial cross-platform

### PR DESCRIPTION
**Pull request by carolynvs**
* Add PowerShell examples
* Use variable substitution instead of env vars to reduce how often we provide shell-specific examples
* Leave it up to the user how to create the manifest files, the `cat` trick only works on bash.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-1d9bf45d78/)

**Comment by carolynvs** [comment]
@jamiehannaford I noticed that in the deployment section we are putting the word "Deployment" in monospace formatting e.g.

The next step is launching a `Deployment` resource

but we don't do that for service. Mind if I update it to use one or the other to be consistent?

**Comment by carolynvs** [comment]
@jamiehannaford Ready for review.

**Comment by jamiehannaford** [comment]
👍

**Pull request merged**
