### PR TITLE
2016-06-03-weekly-news-pycon-and-release-information

### PR DESCRIPTION
**Pull request by kimtryce**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-7d5104681c/)

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-8e06ba0b2c/). :bow:

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-e7b0100732/). :bow:

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-8750684f57/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-fb6933efb1/)

**Comment by kmsholcomb** [comment]
Hey @kimtryce. See my suggested markup in the attached PDF. Let me know if you have any questions. Thanks!

[Weekly-news-June-3-2016_editsKH.pdf](https://github.com/getcarina/getcarina.com/files/298065/Weekly-news-June-3-2016_editsKH.pdf)

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-bf03eae694/).

**Pull request merged**
