### PR TITLE
Fix links to connect to your cluster

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-7e72378bbe/)

**Comment by carolynvs** [comment]
👍

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-7e72378bbe/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-c3e2dcbb65/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-e67341ff1d/)

**Pull request merged**
