### PR TITLE
Update Create and Connect to a Cluster

### PR DESCRIPTION
**Pull request by carolynvs**
Pointing at master in order to get previews. I will repoint at dev before merging.

### CODE REVIEW

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-530e20978f/)

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-2e3b115c0e/)

**Comment by kmsholcomb** [comment]
HI @carolynvs. My suggested edits are in the attached Word doc (and PDf copy of it). Great job adding the new information! I really had very few edits. But, please let me know if you have any questions. Thanks!

[Create and connect to a cluster_update_editsKH.pdf](https://github.com/getcarina/getcarina.com/files/567489/Create.and.connect.to.a.cluster_update_editsKH.pdf)
[Create and connect to a cluster_update_editsKH.docx](https://github.com/getcarina/getcarina.com/files/567488/Create.and.connect.to.a.cluster_update_editsKH.docx)

**Comment by rackernexus** [comment]
:mag_right: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-0ce12dad27/)

**Comment by carolynvs** [comment]
Thanks @kmsholcomb! Some of the suggestions, such as linking to the split getting started guides or to kubernetes 101, will happen once that content has been created. Otherwise I think I got everything. 👍

**Pull request merged**
