### PR TITLE
Run a web server and get the same IP address every time

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by carolynvs** [comment]
Should the `--net mynetwork` be there?

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-062e6843db/)

**Comment by everett-toews** [comment]
Yep. I want to always encourage use of overlay networks everywhere, especially in cases of where we're talking about exposing particular containers publicly.

Do you think I should include a `docker network create mynetwork` command too?

**Comment by carolynvs** [comment]
Nah, I don't think so. Calling it `mynetwork` makes it pretty clear that it isn't some special network that already exists. I just wasn't sure if the custom network was required to make the tip work or not. :smile:

**Pull request merged**
