### PR TITLE
Clarify where to find username

### PR DESCRIPTION
**Pull request by carolynvs**
People are still confused when going through this tutorial about what their username is. I think it would help to say exactly where to find it in the control panel and hint that it is probably your email address. 

I realize we mention this info higher up in the doc, but by the time they get to exporting variables, I often see frustrated users unsure what to enter.

I'm not sure this is the best wording but wanted to throw something out there.

/cc @kmsholcomb @everett-toews

### CODE REVIEW

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-49d97921ef/)

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-188805b097/)

**Comment by kmsholcomb** [comment]
@carolynvs. Looks great to me! :+1:

**Comment by everett-toews** [comment]
👍

**Pull request merged**
