### PR TITLE
Add a reference guide about Carina/Docker images

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by zack-shoylev** [comment]
This needs more content. @everett-toews we were talking about this 1-2 weeks ago. This is mostly a placeholder that starts this particular guide, but it will likely need more contributions from people who know more about images and some direction about what is relevant to Carina.

**Comment by everett-toews** [comment]
This will need to reference https://github.com/getcarina/getcarina.com/issues/727 once it's published.

**Comment by kimtryce** [comment]
This may better live within the Container Sprint now.  @everett-toews thoughts?

**Comment by everett-toews** [comment]
👍 

Please close this once there's a new ticket for it.

**Comment by kimtryce** [comment]
Have created [CON-484](https://jira.rax.io/browse/CON-484) to capture this in the Jira/Containers sprint.

**Pull request closed without merging**
