### PR TITLE
Weekly news

### LINKED ISSUE #776: Weekly news blog post for 2016-04-01

### PR DESCRIPTION
**Pull request by everett-toews**
Still needs images.

Closes #776

### CODE REVIEW

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-124b33f58c/). :bow:

**Comment by jnoller** [comment]
http://s3.amazonaws.com/kidzworld_photo/images/2011424/d8fc8a43-834b-4f48-b5c1-6315d94b6da9/gallery_a%20gallerty.jpg

http://www.charlotteobserver.com/news/local/b5xa1c/picture10894622/ALTERNATES/FREE_640/STUPID_PET_TRICKS_02.JPG.JPG

http://globalnewsconnect.com/wp-content/uploads/2015/08/ee2dc_corgi-tapgif.gif

@everett-toews

**Comment by carolynvs** [comment]
I love that corgi pic! :+1:

**Comment by everett-toews** [comment]
I'm a sucker for skateboarding bull dogs.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-1e3dd375d4/).

**Comment by rackernexus** [comment]
Your content preview [is now ready](https://staging.developer.rackspace.com/getcarina.com/build-8db8dfbf4e/). :bow:

**Comment by rackernexus** [comment]
HULK [PREVIEW](https://staging.developer.rackspace.com/getcarina.com/build-88ac64f0f3/)

**Pull request merged**
