### PR TITLE
Carina contest at PyCon 2016

### PR DESCRIPTION
**Pull request by everett-toews**

### CODE REVIEW

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-e712b9f6f9/).

**Comment by carolynvs** [comment]
I am looking forward to pics of all the cows hoofing it past the booth.

**Comment by rackernexus** [comment]
If you want to double-check your formatting, check [the preview](https://staging.developer.rackspace.com/getcarina.com/build-06c2bfb8f4/).

**Comment by rackernexus** [comment]
:eyes: [Preview](https://staging.developer.rackspace.com/getcarina.com/build-fa7feecb42/)

**Pull request merged**
