### PR TITLE
Test Drive UCP

### PR DESCRIPTION
**Pull request by jnoller**
Blog post to rapidly test drive UCP

### CODE REVIEW

**Comment by kmsholcomb** [comment]
Hi @jnoller: The attached Word doc has my suggested edits and some questions. (The attached PDF is just a copy of the Word doc, in case you would rather work with a PDF). Please let me know if you have any questions. Thanks!

[The fastest Docker UCP test drive_editsKH.pdf](https://github.com/getcarina/getcarina.com/files/167736/The.fastest.Docker.UCP.test.drive_editsKH.pdf)
[The fastest Docker UCP test drive_editsKH.docx](https://github.com/getcarina/getcarina.com/files/167737/The.fastest.Docker.UCP.test.drive_editsKH.docx)

**Comment by rgbkrk** [comment]
The UCP simple script can be trimmed down a bit to:

```
carina create --wait ucp
carina credentials ucp
eval "$(carina env ucp)"
UCP_ADMIN_USER='admin'
read -s  -p "Enter your password and press [ENTER]: ": password 
docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock \
  -e UCP_ADMIN_USER=$UCP_ADMIN_USER -e UCP_ADMIN_PASSWORD=$password \
  --name ucp docker/ucp install --swarm-port 2377 --fresh-install
```

**Comment by rgbkrk** [comment]
Steps I wasn't sure of:

* Do I need to setup the UCP stuff attached to my account? (I didn't have it before)
* Do I care about the trusted registry they suggest?
* What should users do about the license?

screenshot 2016-03-10 12 31 47

I'm clicking skip for now.

**Comment by rgbkrk** [comment]
Even with my feedback, I'd say we could push this out and update more after. Still some kinks to work out, though some of that is flow on Docker's end. Hopefully we'd be able to provide that feedback to make their experience consistent and awesome.

**Comment by rgbkrk** [comment]
Woo, working quite well.

screenshot 2016-03-10 12 43 53

**Comment by rgbkrk** [comment]
Had to go through the license upload tomfoolery and figure out what my account was missing. All set now.

**Comment by jnoller** [comment]
updated

**Comment by jnoller** [comment]
merge away if I'm afk

**Comment by rgbkrk** [comment]
Look good. :shipit:

**Pull request merged**
